task_homepage:
    path:     /tasks
    defaults: { _controller: TaskBundle:Default:index }

task_delete:
    path:     /task_delete/{id}
    defaults: { _controller: TaskBundle:Default:delete }

task_create:
    path:     /task_create
    defaults: { _controller: TaskBundle:Default:add }

task_update:
    path:     /task_update/{id}
    defaults: { _controller: TaskBundle:Default:update }